name: MUtils-Web
load: STARTUP
version: 132
main: de.miraculixx.mweb.MWeb
api-version: 1.16
authors: [ Miraculixx ]
description: MWeb - Create links to your server files to share them!
website: https://mutils.net
libraries:
  - "org.jetbrains.kotlin:kotlin-stdlib:1.8.20"
  - "org.jetbrains.kotlinx:kotlinx-coroutines-core:1.7.0-Beta"
  - "org.jetbrains.kotlinx:kotlinx-coroutines-jdk8:1.7.0-Beta"
  - "org.jetbrains.kotlinx:kotlinx-serialization-json:1.5.0"
  - "net.axay:kspigot:1.20.1"
  - "io.ktor:ktor-server-core-jvm:2.3.0"
  - "io.ktor:ktor-server-content-negotiation-jvm:2.3.0"
  - "io.ktor:ktor-serialization-kotlinx-json-jvm:2.3.0"
  - "io.ktor:ktor-server-cio-jvm:2.3.0"
  - "commons-codec:commons-codec:1.15"
